ktor:
  deployment:
    host: 0.0.0.0
    port: 8080
  application:
    modules:
      - io.github.pynsze.DatabaseKt.configureDatabase
      - io.github.pynsze.HttpKt.configureHttp
      - io.github.pynsze.MonitoringKt.configureMonitoring
      - io.github.pynsze.SerializationKt.configureSerialization
      - io.github.pynsze.RequestValidationKt.configureRequestValidation
      - io.github.pynsze.StatusPagesKt.configureStatusPages
      - io.github.pynsze.RoutingKt.configureRouting
      - io.github.pynsze.auth.AuthKt.configureAuth

postgres:
  url: "$DB_URL"
  user: "$DB_USER"
  password: "$DB_PASSWORD"

auth:
  session:
    encryptionKey: "$AUTH_SESSION_ENCRYPTION_KEY"
    signingKey: "$AUTH_SESSION_SIGNING_KEY"
    cookieSecure: false # Set to true in production when using HTTPS
    maxAgeSeconds: 3600

